main:
   params: [input]
   steps:
   - init:
       assign:
            - projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            - zone: ${input.zone}
            - machineType: ${input.machineType}
            - diskSize: ${input.diskSize}
            - imageProject: ${input.imageProject}
            - imageFamily: ${input.imageFamily}
            - vmName: ${input.vmName}
            - email: ${input.email}
   - createResource:
       call: googleapis.compute.v1.instances.insert
       args:
           project: ${projectId}
           zone: ${zone}
           body:
               name: ${vmName}
               machineType: ${"projects/" + projectId + "/zones/" + zone + "/machineTypes/" + machineType}
               disks:
                - initializeParams:
                    diskSizeGb: ${diskSize}
                    sourceImage: ${"projects/" + imageProject + "/global/images/family/" + imageFamily}
                  type: PERSISTENT
                  boot: true
                  autoDelete: true
               networkInterfaces:
                - network: "global/networks/default"
       result: insertResult
   - retStep:
       return: ${insertResult}